### ISSUE TITLE
RC1 Feedback

### ISSUE THREAD

**Issue by iqbal128855** [SCCapstone/WorkAnyPlace#144]
Can create account and log in. Can accept/delete jobs. Search is working. The text in the UI is hard to read in some instances. I can create new jobs and save it for later use. The ownership of post is also working while deleting. The messages are working. The UI is not very comfortable to use. Cannot log out of the app. The settings can be updated. There is no instructions how to set new password. username etc.

**Comment by brandonrace** [comment]
https://github.com/SCCapstone/WorkAnyPlace/commit/7c59b91f906b187b4ad19b05bdb57c8210923eab

**Comment by brandonrace** [comment]
https://github.com/SCCapstone/WorkAnyPlace/commit/69b1513081aa0c242884bd56921cdf51b83eabff
