### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by brandonrace** [SCCapstone/WorkAnyPlace#193]
To access our website, create a new account and it will pull up a Welcome page which is our website.

**Comment by brandonrace** [comment]
https://workanyplace-62a66.web.app/

**Comment by josemvidal** [comment]
[Website milestone](https://capstone.cse.sc.edu/milestone/website/#i-built-a-webapp)
![image](https://user-images.githubusercontent.com/228704/115862676-6a956e80-a402-11eb-9db1-81f77ae77e17.png)

> If you built a webapp then you do not need to use github pages (but you can, if it makes sense). Instead, your main page should become a splash page which sells your app and shows the video to the user. Make sure you add all the required pages (see above) to your website.

Your homepage is not a splashcreen that sells your app. Your homepage is a login prompt.


Also, login does not work so cannot see anything:

![image](https://user-images.githubusercontent.com/228704/115862864-a9c3bf80-a402-11eb-9711-d103793c87dc.png)

**Comment by brandonrace** [comment]
We decided it would make more sense to see the splash page upon creating a new account instead of seeing it before/when you log in every time.  Therefore when you make a new account it will take you to this page after you type in your information.  As far as the login button, you can’t click it until you type in a username and password.

**Comment by josemvidal** [comment]
Got it, you decided against doing what the Milestone said to do.
